name: ci

on: [push, pull_request]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4

    - name: Test
      run: make test

    - name: Build
      run: make ke

    - uses: actions/upload-artifact@v2
      if: github.event_name == 'push'
      with:
        name: kubeeye
        path: ke
